server:
  port: 9000
  
spring:
  datasource:
    url: jdbc:h2:mem:movies
    username: sa
    password: 
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect